# Generated by Django 5.2.6 on 2025-09-24 08:59

import apps.users.utils
import apps.users.validators
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='images/avatars/', validators=[apps.users.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='myuser',
            name='color',
            field=colorfield.fields.ColorField(default=apps.users.utils.generate_random_color, image_field=None, max_length=25, samples=None),
        ),
    ]
